// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlbVbhYL8F2B-ckGTYf3lR8Zu11VLuKNo',
    appId: '1:133485594821:web:061f5a3166b10e406a48ac',
    messagingSenderId: '133485594821',
    projectId: 'local-finder-c25fd',
    authDomain: 'local-finder-c25fd.firebaseapp.com',
    storageBucket: 'local-finder-c25fd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASLGdPDTRMAKnEwKcA0ejj16NTcbJNA5Q',
    appId: '1:133485594821:android:c8182ebf8e0635e76a48ac',
    messagingSenderId: '133485594821',
    projectId: 'local-finder-c25fd',
    storageBucket: 'local-finder-c25fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_0K85_8b0r8STnRTRcmyiQzXeTz31pgg',
    appId: '1:133485594821:ios:a59bcbb0ca4b42166a48ac',
    messagingSenderId: '133485594821',
    projectId: 'local-finder-c25fd',
    storageBucket: 'local-finder-c25fd.firebasestorage.app',
    iosBundleId: 'com.example.localFinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_0K85_8b0r8STnRTRcmyiQzXeTz31pgg',
    appId: '1:133485594821:ios:a59bcbb0ca4b42166a48ac',
    messagingSenderId: '133485594821',
    projectId: 'local-finder-c25fd',
    storageBucket: 'local-finder-c25fd.firebasestorage.app',
    iosBundleId: 'com.example.localFinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlbVbhYL8F2B-ckGTYf3lR8Zu11VLuKNo',
    appId: '1:133485594821:web:abd0382b865893e56a48ac',
    messagingSenderId: '133485594821',
    projectId: 'local-finder-c25fd',
    authDomain: 'local-finder-c25fd.firebaseapp.com',
    storageBucket: 'local-finder-c25fd.firebasestorage.app',
  );
}
